-- This script is only used to properly load files

local Cacheblock={["Quad"]={},["Canvas"]={},["Audio"]={},["Font"]={},["Video"]={},["Map"]={}}

function Cacheblock.Audio.new()

  local audio={}
  
  function audio.add(type)
  
  end

end

function Cacheblock.Canvas.new()

  local canvas={}
  
  function canvas.add()
  
  end

end

function Cacheblock.Font.new()

  local font={["content"]={}}
  
  function font.add(name,path,pix)
  
    table.insert(font.content,name)
    font.content[name]={path=path,font=love.graphics.newFont(path,pix)}
  
  end
  
  function font.del(name)
  
    font.content[name]=nil
    love.graphics.setNewFont()
  
  end
  
  function font.setmain(name)
  
    love.graphics.setFont(font.content[name].font)
  
  end
 
  return font

end

function Cacheblock.Video.new()

  local video={}

end

function Cacheblock.Map.new()

  local map={}

end

function Cacheblock.Quad.new()

  local quad={}
  
  function quad.add(type,method,name)
  
  end

end

return Cacheblock
